[package]
name = "latency"
version = "0.1.0"
authors = ["David Zmick <david@dpzmick.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
affinity = "0.1.1"
